# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo4_praca_inzynierska.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1082, 750)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #272727")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_top_menus = QtWidgets.QFrame(self.centralwidget)
        self.frame_top_menus.setGeometry(QtCore.QRect(0, 0, 190, 701))
        self.frame_top_menus.setStyleSheet("background-color:rgb(44, 42, 43)")
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.list_of_trainees_navbutton = QtWidgets.QPushButton(self.frame_top_menus)
        self.list_of_trainees_navbutton.setGeometry(QtCore.QRect(0, 160, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        self.list_of_trainees_navbutton.setFont(font)
        self.list_of_trainees_navbutton.setStyleSheet("color: #ffffff;\n"
"text-align: left center;\n"
"padding-left: 31px;\n"
"background: rgba(255, 255, 255, 0);\n"
"border: 0px solid rgba(255, 255, 255, 0);\n"
"qproperty-icon: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/list.png);\n"
"qproperty-iconSize: 20px;\n"
"")
        self.list_of_trainees_navbutton.setObjectName("list_of_trainees_navbutton")
        self.add_training_navbutton = QtWidgets.QPushButton(self.frame_top_menus)
        self.add_training_navbutton.setGeometry(QtCore.QRect(0, 220, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        self.add_training_navbutton.setFont(font)
        self.add_training_navbutton.setStyleSheet("color: #ffffff;\n"
"text-align: left center;\n"
"padding-left: 30px;\n"
"background: rgba(255, 255, 255, 0);\n"
"border: 0px solid rgba(255, 255, 255, 0);\n"
"qproperty-icon: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/add_training.png);\n"
"qproperty-iconSize: 25px;")
        self.add_training_navbutton.setObjectName("add_training_navbutton")
        self.generate_report_navbutton = QtWidgets.QPushButton(self.frame_top_menus)
        self.generate_report_navbutton.setGeometry(QtCore.QRect(0, 280, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        self.generate_report_navbutton.setFont(font)
        self.generate_report_navbutton.setStyleSheet("color: #ffffff;\n"
"text-align: left center;\n"
"padding-left: 34px;\n"
"background: rgba(255, 255, 255, 0);\n"
"border: 0px solid rgba(255, 255, 255, 0);\n"
"qproperty-icon: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/report.png);\n"
"qproperty-iconSize: 21px;\n"
"")
        self.generate_report_navbutton.setObjectName("generate_report_navbutton")
        self.menu_navbutton = QtWidgets.QPushButton(self.frame_top_menus)
        self.menu_navbutton.setGeometry(QtCore.QRect(0, 100, 191, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        self.menu_navbutton.setFont(font)
        self.menu_navbutton.setStyleSheet("color: #ffffff;\n"
"text-align: left center;\n"
"padding-left: 30px;\n"
"background: rgba(255, 255, 255, 0);\n"
"border: 0px solid rgba(255, 255, 255, 0);\n"
"qproperty-icon: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/home.png);\n"
"qproperty-iconSize: 20px;")
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.menu_navbutton.setIcon(icon)
        self.menu_navbutton.setIconSize(QtCore.QSize(20, 20))
        self.menu_navbutton.setObjectName("menu_navbutton")
        self.instruction_button = QtWidgets.QPushButton(self.frame_top_menus)
        self.instruction_button.setGeometry(QtCore.QRect(0, 630, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        self.instruction_button.setFont(font)
        self.instruction_button.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left center;\n"
"padding-left: 20px;\n"
"")
        self.instruction_button.setObjectName("instruction_button")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(190, 40, 881, 671))
        self.frame.setMaximumSize(QtCore.QSize(881, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setStyleSheet("background-color: rgba(255,255,255,0);")
        self.main_page.setObjectName("main_page")
        self.frame_3 = QtWidgets.QFrame(self.main_page)
        self.frame_3.setGeometry(QtCore.QRect(70, 50, 721, 141))
        self.frame_3.setStyleSheet("background-color: rgb(54, 52, 53);\n"
"border: 2px solid;\n"
"border-color: rgb(54, 52, 53);\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(30, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(320, 20, 451, 151))
        self.label_3.setStyleSheet("background-image: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/wave1.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(400, 10, 361, 131))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/wave2.png);\n"
"border: 0px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(40, 60, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255,255,255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_5.setObjectName("label_5")
        self.frame_4 = QtWidgets.QFrame(self.main_page)
        self.frame_4.setGeometry(QtCore.QRect(70, 220, 341, 191))
        self.frame_4.setStyleSheet("background-color: rgb(54, 52, 53);\n"
"border: 2px solid;\n"
"border-color: rgb(54, 52, 53);\n"
"border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setObjectName("label_6")
        self.list_of_trainees_menu_button = QtWidgets.QPushButton(self.frame_4)
        self.list_of_trainees_menu_button.setGeometry(QtCore.QRect(220, 133, 101, 41))
        self.list_of_trainees_menu_button.setStyleSheet("qproperty-icon: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/arrow.png);\n"
"qproperty-iconSize: 20px;\n"
"background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;")
        self.list_of_trainees_menu_button.setText("")
        self.list_of_trainees_menu_button.setObjectName("list_of_trainees_menu_button")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(30, 70, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_9.setObjectName("label_9")
        self.frame_5 = QtWidgets.QFrame(self.main_page)
        self.frame_5.setGeometry(QtCore.QRect(450, 220, 341, 191))
        self.frame_5.setStyleSheet("background-color: rgb(54, 52, 53);\n"
"border: 2px solid;\n"
"border-color: rgb(54, 52, 53);\n"
"border-radius: 10px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;")
        self.label_8.setObjectName("label_8")
        self.add_trainee_menu_button = QtWidgets.QPushButton(self.frame_5)
        self.add_trainee_menu_button.setGeometry(QtCore.QRect(220, 133, 101, 41))
        self.add_trainee_menu_button.setStyleSheet("qproperty-icon: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/arrow.png);\n"
"qproperty-iconSize: 20px;\n"
"background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;")
        self.add_trainee_menu_button.setText("")
        self.add_trainee_menu_button.setObjectName("add_trainee_menu_button")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(30, 70, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_10.setObjectName("label_10")
        self.frame_6 = QtWidgets.QFrame(self.main_page)
        self.frame_6.setGeometry(QtCore.QRect(70, 440, 721, 121))
        self.frame_6.setStyleSheet("background-color: rgb(54, 52, 53);\n"
"border: 2px solid;\n"
"border-color: rgb(54, 52, 53);\n"
"border-radius: 10px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(30, 0, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_11.setObjectName("label_11")
        self.generate_report_menu_button = QtWidgets.QPushButton(self.frame_6)
        self.generate_report_menu_button.setGeometry(QtCore.QRect(600, 60, 101, 41))
        self.generate_report_menu_button.setStyleSheet("qproperty-icon: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/arrow.png);\n"
"qproperty-iconSize: 20px;\n"
"background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;")
        self.generate_report_menu_button.setText("")
        self.generate_report_menu_button.setObjectName("generate_report_menu_button")
        self.label_12 = QtWidgets.QLabel(self.frame_6)
        self.label_12.setGeometry(QtCore.QRect(30, 40, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border: 0px;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(-50, 0, 501, 131))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/wave3_1.png);\n"
"border: 0px;")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_13.raise_()
        self.label_11.raise_()
        self.generate_report_menu_button.raise_()
        self.label_12.raise_()
        self.stackedWidget.addWidget(self.main_page)
        self.add_trainee_page = QtWidgets.QWidget()
        self.add_trainee_page.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: white;")
        self.add_trainee_page.setObjectName("add_trainee_page")
        self.name_lineEdit = QtWidgets.QLineEdit(self.add_trainee_page)
        self.name_lineEdit.setGeometry(QtCore.QRect(222, 150, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_lineEdit.setFont(font)
        self.name_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.name_label = QtWidgets.QLabel(self.add_trainee_page)
        self.name_label.setGeometry(QtCore.QRect(90, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.name_label.setObjectName("name_label")
        self.surname_label = QtWidgets.QLabel(self.add_trainee_page)
        self.surname_label.setGeometry(QtCore.QRect(90, 200, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.surname_label.setFont(font)
        self.surname_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.surname_label.setObjectName("surname_label")
        self.date_of_birth_label = QtWidgets.QLabel(self.add_trainee_page)
        self.date_of_birth_label.setGeometry(QtCore.QRect(90, 250, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.date_of_birth_label.setFont(font)
        self.date_of_birth_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.date_of_birth_label.setObjectName("date_of_birth_label")
        self.email_label = QtWidgets.QLabel(self.add_trainee_page)
        self.email_label.setGeometry(QtCore.QRect(90, 300, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.email_label.setObjectName("email_label")
        self.add_start_date_training_label = QtWidgets.QLabel(self.add_trainee_page)
        self.add_start_date_training_label.setGeometry(QtCore.QRect(90, 460, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.add_start_date_training_label.setFont(font)
        self.add_start_date_training_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.add_start_date_training_label.setObjectName("add_start_date_training_label")
        self.phone_label = QtWidgets.QLabel(self.add_trainee_page)
        self.phone_label.setGeometry(QtCore.QRect(90, 350, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.phone_label.setFont(font)
        self.phone_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.phone_label.setObjectName("phone_label")
        self.squat_label = QtWidgets.QLabel(self.add_trainee_page)
        self.squat_label.setGeometry(QtCore.QRect(490, 260, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.squat_label.setFont(font)
        self.squat_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.squat_label.setObjectName("squat_label")
        self.benchpress_label = QtWidgets.QLabel(self.add_trainee_page)
        self.benchpress_label.setGeometry(QtCore.QRect(490, 320, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.benchpress_label.setFont(font)
        self.benchpress_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.benchpress_label.setObjectName("benchpress_label")
        self.deadlift_label = QtWidgets.QLabel(self.add_trainee_page)
        self.deadlift_label.setGeometry(QtCore.QRect(490, 370, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.deadlift_label.setFont(font)
        self.deadlift_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.deadlift_label.setObjectName("deadlift_label")
        self.add_trainee_title = QtWidgets.QLabel(self.add_trainee_page)
        self.add_trainee_title.setGeometry(QtCore.QRect(70, 70, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.add_trainee_title.setFont(font)
        self.add_trainee_title.setObjectName("add_trainee_title")
        self.surname_lineEdit = QtWidgets.QLineEdit(self.add_trainee_page)
        self.surname_lineEdit.setGeometry(QtCore.QRect(220, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.surname_lineEdit.setFont(font)
        self.surname_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.surname_lineEdit.setObjectName("surname_lineEdit")
        self.email_lineEdit = QtWidgets.QLineEdit(self.add_trainee_page)
        self.email_lineEdit.setGeometry(QtCore.QRect(220, 300, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_lineEdit.setFont(font)
        self.email_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.phone_lineEdit = QtWidgets.QLineEdit(self.add_trainee_page)
        self.phone_lineEdit.setGeometry(QtCore.QRect(260, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phone_lineEdit.setFont(font)
        self.phone_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.phone_lineEdit.setObjectName("phone_lineEdit")
        self.PR_title = QtWidgets.QLabel(self.add_trainee_page)
        self.PR_title.setGeometry(QtCore.QRect(470, 200, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.PR_title.setFont(font)
        self.PR_title.setObjectName("PR_title")
        self.benchpress_lineEdit = QtWidgets.QLineEdit(self.add_trainee_page)
        self.benchpress_lineEdit.setGeometry(QtCore.QRect(650, 320, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.benchpress_lineEdit.setFont(font)
        self.benchpress_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.benchpress_lineEdit.setObjectName("benchpress_lineEdit")
        self.deadlift_lineEdit = QtWidgets.QLineEdit(self.add_trainee_page)
        self.deadlift_lineEdit.setGeometry(QtCore.QRect(650, 370, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deadlift_lineEdit.setFont(font)
        self.deadlift_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.deadlift_lineEdit.setObjectName("deadlift_lineEdit")
        self.squat_lineEdit = QtWidgets.QLineEdit(self.add_trainee_page)
        self.squat_lineEdit.setGeometry(QtCore.QRect(650, 260, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.squat_lineEdit.setFont(font)
        self.squat_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.squat_lineEdit.setObjectName("squat_lineEdit")
        self.deadlift_kg_label = QtWidgets.QLabel(self.add_trainee_page)
        self.deadlift_kg_label.setGeometry(QtCore.QRect(710, 260, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.deadlift_kg_label.setFont(font)
        self.deadlift_kg_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.deadlift_kg_label.setObjectName("deadlift_kg_label")
        self.benchpress_kg_label = QtWidgets.QLabel(self.add_trainee_page)
        self.benchpress_kg_label.setGeometry(QtCore.QRect(710, 320, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.benchpress_kg_label.setFont(font)
        self.benchpress_kg_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.benchpress_kg_label.setObjectName("benchpress_kg_label")
        self.squat_kg_label = QtWidgets.QLabel(self.add_trainee_page)
        self.squat_kg_label.setGeometry(QtCore.QRect(710, 370, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.squat_kg_label.setFont(font)
        self.squat_kg_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.squat_kg_label.setObjectName("squat_kg_label")
        self.weight_label = QtWidgets.QLabel(self.add_trainee_page)
        self.weight_label.setGeometry(QtCore.QRect(90, 400, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.weight_label.setFont(font)
        self.weight_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.weight_label.setObjectName("weight_label")
        self.weight_lineEdit = QtWidgets.QLineEdit(self.add_trainee_page)
        self.weight_lineEdit.setGeometry(QtCore.QRect(300, 400, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.weight_lineEdit.setFont(font)
        self.weight_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.weight_lineEdit.setObjectName("weight_lineEdit")
        self.squat_kg_label_3 = QtWidgets.QLabel(self.add_trainee_page)
        self.squat_kg_label_3.setGeometry(QtCore.QRect(350, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.squat_kg_label_3.setFont(font)
        self.squat_kg_label_3.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.squat_kg_label_3.setObjectName("squat_kg_label_3")
        self.date_of_birth_dateEdit = QtWidgets.QDateEdit(self.add_trainee_page)
        self.date_of_birth_dateEdit.setGeometry(QtCore.QRect(260, 250, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_of_birth_dateEdit.setFont(font)
        self.date_of_birth_dateEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.date_of_birth_dateEdit.setObjectName("date_of_birth_dateEdit")
        self.add_start_date_training_dateEdit = QtWidgets.QDateEdit(self.add_trainee_page)
        self.add_start_date_training_dateEdit.setGeometry(QtCore.QRect(260, 490, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_start_date_training_dateEdit.setFont(font)
        self.add_start_date_training_dateEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;")
        self.add_start_date_training_dateEdit.setObjectName("add_start_date_training_dateEdit")
        self.add_trainee_button = QtWidgets.QPushButton(self.add_trainee_page)
        self.add_trainee_button.setGeometry(QtCore.QRect(640, 550, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_trainee_button.setFont(font)
        self.add_trainee_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.add_trainee_button.setObjectName("add_trainee_button")
        self.label_7 = QtWidgets.QLabel(self.add_trainee_page)
        self.label_7.setGeometry(QtCore.QRect(340, 500, 531, 161))
        self.label_7.setStyleSheet("background-image: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/wave1.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_14 = QtWidgets.QLabel(self.add_trainee_page)
        self.label_14.setGeometry(QtCore.QRect(0, 540, 491, 111))
        self.label_14.setStyleSheet("background-image: url(D:/ProjectsPython/demo3_praca_inz/src/gui/resources/wave3_1.png);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.name_lineEdit.raise_()
        self.name_label.raise_()
        self.surname_label.raise_()
        self.date_of_birth_label.raise_()
        self.email_label.raise_()
        self.add_start_date_training_label.raise_()
        self.phone_label.raise_()
        self.squat_label.raise_()
        self.benchpress_label.raise_()
        self.deadlift_label.raise_()
        self.add_trainee_title.raise_()
        self.surname_lineEdit.raise_()
        self.email_lineEdit.raise_()
        self.phone_lineEdit.raise_()
        self.PR_title.raise_()
        self.benchpress_lineEdit.raise_()
        self.deadlift_lineEdit.raise_()
        self.squat_lineEdit.raise_()
        self.deadlift_kg_label.raise_()
        self.benchpress_kg_label.raise_()
        self.squat_kg_label.raise_()
        self.weight_label.raise_()
        self.weight_lineEdit.raise_()
        self.squat_kg_label_3.raise_()
        self.date_of_birth_dateEdit.raise_()
        self.add_start_date_training_dateEdit.raise_()
        self.label_7.raise_()
        self.label_14.raise_()
        self.add_trainee_button.raise_()
        self.stackedWidget.addWidget(self.add_trainee_page)
        self.generate_report_page = QtWidgets.QWidget()
        self.generate_report_page.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: white;")
        self.generate_report_page.setObjectName("generate_report_page")
        self.title_generate_report_page = QtWidgets.QLabel(self.generate_report_page)
        self.title_generate_report_page.setGeometry(QtCore.QRect(70, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.title_generate_report_page.setFont(font)
        self.title_generate_report_page.setObjectName("title_generate_report_page")
        self.add_photos_button = QtWidgets.QPushButton(self.generate_report_page)
        self.add_photos_button.setGeometry(QtCore.QRect(440, 190, 171, 251))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.add_photos_button.setFont(font)
        self.add_photos_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.add_photos_button.setObjectName("add_photos_button")
        self.add_film_button = QtWidgets.QPushButton(self.generate_report_page)
        self.add_film_button.setGeometry(QtCore.QRect(140, 190, 171, 251))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.add_film_button.setFont(font)
        self.add_film_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.add_film_button.setObjectName("add_film_button")
        self.stackedWidget.addWidget(self.generate_report_page)

        self.report_page = QtWidgets.QWidget()
        self.report_page.setObjectName("report_page")
        self.report_photo = QtWidgets.QLabel(self.report_page)
        self.report_photo.setGeometry(QtCore.QRect(20, 30, 391, 531))
        self.report_photo.setObjectName("report_photo")
        self.report_comment = QtWidgets.QPlainTextEdit(self.report_page)
        self.report_comment.setGeometry(QtCore.QRect(480, 110, 331, 421))
        self.report_comment.setObjectName("report_comment")
        self.label_15 = QtWidgets.QLabel(self.report_page)
        self.label_15.setGeometry(QtCore.QRect(490, 50, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: white;")
        self.label_15.setObjectName("label_15")
        self.prev_photo_button = QtWidgets.QPushButton(self.report_page)
        self.prev_photo_button.setGeometry(QtCore.QRect(180, 570, 41, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.prev_photo_button.setFont(font)
        self.prev_photo_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
                                             "border: 0px;\n"
                                             "border-radius: 10px;\n"
                                             "color: white;")
        self.prev_photo_button.setObjectName("prev_photo_button")
        self.next_photo_button = QtWidgets.QPushButton(self.report_page)
        self.next_photo_button.setGeometry(QtCore.QRect(230, 570, 41, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.next_photo_button.setFont(font)
        self.next_photo_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
                                             "border: 0px;\n"
                                             "border-radius: 10px;\n"
                                             "color: white;")
        self.next_photo_button.setObjectName("next_photo_button")
        self.save_report = QtWidgets.QPushButton(self.report_page)
        self.save_report.setGeometry(QtCore.QRect(650, 570, 161, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.save_report.setFont(font)
        self.save_report.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
                                      "border: 0px;\n"
                                      "border-radius: 10px;\n"
                                      "color: white;")
        self.save_report.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.report_page)
        #...
        self.view_training_page = QtWidgets.QWidget()
        self.view_training_page.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: white;")
        self.view_training_page.setObjectName("view_training_page")
        self.title_view_training_page = QtWidgets.QLabel(self.view_training_page)
        self.title_view_training_page.setGeometry(QtCore.QRect(70, 70, 301, 51))
        self.title_training = QtWidgets.QLabel(self.view_training_page)
        self.title_training.setGeometry(QtCore.QRect(70, 130, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.title_view_training_page.setFont(font)
        self.title_view_training_page.setObjectName("title_view_training_page")
        font.setPointSize(12)
        self.title_training.setFont(font)
        self.title_training.setObjectName("title_training")
        self.training_table = QtWidgets.QTableWidget(self.view_training_page)
        self.training_table.setGeometry(QtCore.QRect(100, 220, 628, 331))
        self.training_table.setObjectName("training_table")
        self.training_table.setColumnCount(0)
        self.training_table.setRowCount(0)

        headers = ['Nazwa ćwiczenia', 'Serie', 'Powtórzenia', 'Opis']
        self.training_table.setColumnCount(len(headers))
        self.training_table.setHorizontalHeaderLabels(headers)
        self.training_table.setColumnWidth(1, 110)
        self.training_table.setColumnWidth(2, 110)
        self.training_table.setColumnWidth(3, 200)
        self.training_table.setStyleSheet("""
                     QTableWidget#training_table {
                         background-color: rgba(255, 255, 255, 0);
                         color: white;
                         gridline-color: white;
                         border: 0px solid white;
                     }
                     QTableWidget#training_table::item {
                         background-color: rgba(255, 255, 255, 0);
                         color: white;
                     }
                     QTableWidget#training_table QHeaderView::section {
                         background-color: white;
                         color: black;
                     }
                 """)




        self.prev_training_button = QtWidgets.QPushButton(self.view_training_page)
        self.prev_training_button.setGeometry(QtCore.QRect(660, 580, 41, 41))
        self.prev_training_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.prev_training_button.setObjectName("prev_training_button")
        self.next_training_button = QtWidgets.QPushButton(self.view_training_page)
        self.next_training_button.setGeometry(QtCore.QRect(710, 580, 41, 41))
        self.next_training_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.next_training_button.setObjectName("next_training_button")
        self.stackedWidget.addWidget(self.view_training_page)
        self.view_trainee_page = QtWidgets.QWidget()
        self.view_trainee_page.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: white;")
        self.view_trainee_page.setObjectName("view_trainee_page")
        self.email_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.email_label_2.setGeometry(QtCore.QRect(80, 240, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.email_label_2.setFont(font)
        self.email_label_2.setObjectName("email_label_2")
        self.benchpress_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.benchpress_label_2.setGeometry(QtCore.QRect(500, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.benchpress_label_2.setFont(font)
        self.benchpress_label_2.setObjectName("benchpress_label_2")
        self.benchpress_kg_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.benchpress_kg_label_2.setGeometry(QtCore.QRect(740, 250, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.benchpress_kg_label_2.setFont(font)
        self.benchpress_kg_label_2.setObjectName("benchpress_kg_label_2")
        self.date_of_birth_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.date_of_birth_label_2.setGeometry(QtCore.QRect(80, 180, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.date_of_birth_label_2.setFont(font)
        self.date_of_birth_label_2.setObjectName("date_of_birth_label_2")
        self.squat_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.squat_label_2.setGeometry(QtCore.QRect(500, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.squat_label_2.setFont(font)
        self.squat_label_2.setObjectName("squat_label_2")
        self.phone_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.phone_label_2.setGeometry(QtCore.QRect(80, 290, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.phone_label_2.setFont(font)
        self.phone_label_2.setObjectName("phone_label_2")
        self.PR_title_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.PR_title_2.setGeometry(QtCore.QRect(470, 140, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.PR_title_2.setFont(font)
        self.PR_title_2.setObjectName("PR_title_2")
        self.weight_kg_label = QtWidgets.QLabel(self.view_trainee_page)
        self.weight_kg_label.setGeometry(QtCore.QRect(340, 340, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.weight_kg_label.setFont(font)
        self.weight_kg_label.setObjectName("weight_kg_label")
        self.name_surname_dblabel = QtWidgets.QLabel(self.view_trainee_page)
        self.name_surname_dblabel.setGeometry(QtCore.QRect(70, 70, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.name_surname_dblabel.setFont(font)
        self.name_surname_dblabel.setObjectName("name_surname_dblabel")
        self.weight_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.weight_label_2.setGeometry(QtCore.QRect(80, 340, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.weight_label_2.setFont(font)
        self.weight_label_2.setObjectName("weight_label_2")
        self.squat_kg_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.squat_kg_label_2.setGeometry(QtCore.QRect(740, 200, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.squat_kg_label_2.setFont(font)
        self.squat_kg_label_2.setObjectName("squat_kg_label_2")
        self.add_start_date_training_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.add_start_date_training_label_2.setGeometry(QtCore.QRect(80, 400, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.add_start_date_training_label_2.setFont(font)
        self.add_start_date_training_label_2.setObjectName("add_start_date_training_label_2")
        self.deadlift_label_2 = QtWidgets.QLabel(self.view_trainee_page)
        self.deadlift_label_2.setGeometry(QtCore.QRect(500, 300, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.deadlift_label_2.setFont(font)
        self.deadlift_label_2.setObjectName("deadlift_label_2")
        self.date_of_birth_label_dblabel = QtWidgets.QLabel(self.view_trainee_page)
        self.date_of_birth_label_dblabel.setGeometry(QtCore.QRect(250, 180, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.date_of_birth_label_dblabel.setFont(font)
        self.date_of_birth_label_dblabel.setObjectName("date_of_birth_label_dblabel")
        self.email_dblabel = QtWidgets.QLabel(self.view_trainee_page)
        self.email_dblabel.setGeometry(QtCore.QRect(250, 240, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.email_dblabel.setFont(font)
        self.email_dblabel.setObjectName("email_dblabel")
        self.phone_dblabel = QtWidgets.QLabel(self.view_trainee_page)
        self.phone_dblabel.setGeometry(QtCore.QRect(250, 290, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.phone_dblabel.setFont(font)
        self.phone_dblabel.setObjectName("phone_dblabel")
        self.weight_dblabel = QtWidgets.QLabel(self.view_trainee_page)
        self.weight_dblabel.setGeometry(QtCore.QRect(260, 340, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.weight_dblabel.setFont(font)
        self.weight_dblabel.setObjectName("weight_dblabel")
        self.start_date_training_db_label = QtWidgets.QLabel(self.view_trainee_page)
        self.start_date_training_db_label.setGeometry(QtCore.QRect(260, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.start_date_training_db_label.setFont(font)
        self.start_date_training_db_label.setObjectName("start_date_training_db_label")
        self.squat_dblabel = QtWidgets.QLabel(self.view_trainee_page)
        self.squat_dblabel.setGeometry(QtCore.QRect(680, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.squat_dblabel.setFont(font)
        self.squat_dblabel.setObjectName("squat_dblabel")
        self.benchpress_dblabel = QtWidgets.QLabel(self.view_trainee_page)
        self.benchpress_dblabel.setGeometry(QtCore.QRect(680, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.benchpress_dblabel.setFont(font)
        self.benchpress_dblabel.setObjectName("benchpress_dblabel")
        self.deadlift_dblabel = QtWidgets.QLabel(self.view_trainee_page)
        self.deadlift_dblabel.setGeometry(QtCore.QRect(680, 300, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.deadlift_dblabel.setFont(font)
        self.deadlift_dblabel.setObjectName("deadlift_dblabel")
        self.deadlift_kg_label_3 = QtWidgets.QLabel(self.view_trainee_page)
        self.deadlift_kg_label_3.setGeometry(QtCore.QRect(740, 300, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.deadlift_kg_label_3.setFont(font)
        self.deadlift_kg_label_3.setObjectName("deadlift_kg_label_3")
        self.add_training_trainee_button = QtWidgets.QPushButton(self.view_trainee_page)
        self.add_training_trainee_button.setGeometry(QtCore.QRect(530, 370, 191, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.add_training_trainee_button.setFont(font)
        self.add_training_trainee_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.add_training_trainee_button.setObjectName("add_training_trainee_button")
        font.setPointSize(11)
        self.render_film_button = QtWidgets.QPushButton(self.generate_report_page)
        self.render_film_button.setGeometry(QtCore.QRect(140, 470, 191, 41))
        self.render_film_button.setFont(font)
        self.render_film_button.setStyleSheet("QPushButton:disabled { background-color: rgba(90, 90, 90, 130);"
                                              "color: rgba(150, 150, 150, 255);"
                                              "border: 0px;"
                                              "border-radius: 10px; }"
                                              "QPushButton:checked { background-color: rgba(30, 29, 29, 130);"
                                              "border: 0px;"
                                              "border-radius: 10px; }")

        self.render_film_button.setObjectName("render_film_button")
        self.render_photos_button = QtWidgets.QPushButton(self.generate_report_page)
        self.render_photos_button.setGeometry(QtCore.QRect(440, 470, 191, 41))
        self.render_photos_button.setFont(font)
        self.render_photos_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
                                              "border: 0px;\n"
                                              "border-radius: 10px;")
        self.render_photos_button.setObjectName("render_photos_button")
        self.render_photos_button.setStyleSheet("QPushButton:disabled { background-color: rgba(90, 90, 90, 130);"
                                              "color: rgba(150, 150, 150, 255);"
                                              "border: 0px;"
                                              "border-radius: 10px; }"
                                              "QPushButton:checked { background-color: rgba(30, 29, 29, 130);"
                                              "border: 0px;"
                                              "border-radius: 10px; }")
        self.show_training_trainee_button = QtWidgets.QPushButton(self.view_trainee_page)
        self.show_training_trainee_button.setGeometry(QtCore.QRect(530, 420, 191, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.show_training_trainee_button.setFont(font)
        self.show_training_trainee_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.show_training_trainee_button.setObjectName("show_training_trainee_button")
        self.stackedWidget.addWidget(self.view_trainee_page)
        self.add_training_page = QtWidgets.QWidget()
        self.add_training_page.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: white;")
        self.add_training_page.setObjectName("add_training_page")
        self.title_add_trainig_page = QtWidgets.QLabel(self.add_training_page)
        self.title_add_trainig_page.setGeometry(QtCore.QRect(70, 70, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.title_add_trainig_page.setFont(font)
        self.title_add_trainig_page.setObjectName("title_add_trainig_page")
        self.number_of_reps_lineEdit = QtWidgets.QLineEdit(self.add_training_page)
        self.number_of_reps_lineEdit.setGeometry(QtCore.QRect(250, 250, 221, 41))
        self.number_of_reps_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.number_of_reps_lineEdit.setObjectName("number_of_reps_lineEdit")
        self.name_of_exercise_lineEdit = QtWidgets.QLineEdit(self.add_training_page)
        self.name_of_exercise_lineEdit.setGeometry(QtCore.QRect(260, 150, 211, 41))
        self.name_of_exercise_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.name_of_exercise_lineEdit.setObjectName("name_of_exercise_lineEdit")
        self.number_of_sets_label = QtWidgets.QLabel(self.add_training_page)
        self.number_of_sets_label.setGeometry(QtCore.QRect(90, 200, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.number_of_sets_label.setFont(font)
        self.number_of_sets_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.number_of_sets_label.setObjectName("number_of_sets_label")
        self.number_of_reps_label = QtWidgets.QLabel(self.add_training_page)
        self.number_of_reps_label.setGeometry(QtCore.QRect(90, 250, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.number_of_reps_label.setFont(font)
        self.number_of_reps_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.number_of_reps_label.setObjectName("number_of_reps_label")
        self.name_of_exercise_label = QtWidgets.QLabel(self.add_training_page)
        self.name_of_exercise_label.setGeometry(QtCore.QRect(90, 150, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.name_of_exercise_label.setFont(font)
        self.name_of_exercise_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.name_of_exercise_label.setObjectName("name_of_exercise_label")
        self.number_of_sets_lineEdit = QtWidgets.QLineEdit(self.add_training_page)
        self.number_of_sets_lineEdit.setGeometry(QtCore.QRect(240, 200, 231, 41))
        self.number_of_sets_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.number_of_sets_lineEdit.setObjectName("number_of_sets_lineEdit")
        self.additional_info_label = QtWidgets.QLabel(self.add_training_page)
        self.additional_info_label.setGeometry(QtCore.QRect(90, 300, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.additional_info_label.setFont(font)
        self.additional_info_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.additional_info_label.setObjectName("additional_info_label")
        self.add_training_button = QtWidgets.QPushButton(self.add_training_page)
        self.add_training_button.setGeometry(QtCore.QRect(570, 460, 191, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.add_training_button.setFont(font)
        self.add_training_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.add_training_button.setObjectName("add_training_button")
        self.add_next_excercise_button = QtWidgets.QPushButton(self.add_training_page)
        self.add_next_excercise_button.setGeometry(QtCore.QRect(570, 410, 191, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.add_next_excercise_button.setFont(font)
        self.add_next_excercise_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.add_next_excercise_button.setObjectName("add_next_excercise_button")
        self.exercises_list = QtWidgets.QListView(self.add_training_page)
        self.exercises_list.setGeometry(QtCore.QRect(520, 110, 256, 192))
        self.exercises_list.setObjectName("exercises_list")
        self.additional_info_editText = QtWidgets.QPlainTextEdit(self.add_training_page)
        self.additional_info_editText.setGeometry(QtCore.QRect(93, 360, 381, 171))
        self.additional_info_editText.setObjectName("additional_info_editText")
        self.stackedWidget.addWidget(self.add_training_page)
        self.add_training_name = QtWidgets.QWidget()
        self.add_training_name.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: white;")
        self.add_training_name.setObjectName("add_training_name")
        self.start_date_training_label_2 = QtWidgets.QLabel(self.add_training_name)
        self.start_date_training_label_2.setGeometry(QtCore.QRect(90, 250, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.start_date_training_label_2.setFont(font)
        self.start_date_training_label_2.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.start_date_training_label_2.setObjectName("start_date_training_label_2")
        self.name_of_training = QtWidgets.QLabel(self.add_training_name)
        self.name_of_training.setGeometry(QtCore.QRect(90, 200, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.name_of_training.setFont(font)
        self.name_of_training.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.name_of_training.setObjectName("name_of_training")
        self.name_of_training_lineEdit = QtWidgets.QLineEdit(self.add_training_name)
        self.name_of_training_lineEdit.setGeometry(QtCore.QRect(340, 200, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_of_training_lineEdit.setFont(font)
        self.name_of_training_lineEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.name_of_training_lineEdit.setObjectName("name_of_training_lineEdit")
        self.add_training_title = QtWidgets.QLabel(self.add_training_name)
        self.add_training_title.setGeometry(QtCore.QRect(70, 70, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.add_training_title.setFont(font)
        self.add_training_title.setStyleSheet("color: white;")
        self.add_training_title.setObjectName("add_training_title")
        self.choose_trainee_comboBox = QtWidgets.QComboBox(self.add_training_name)
        self.choose_trainee_comboBox.setGeometry(QtCore.QRect(340, 150, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.choose_trainee_comboBox.setFont(font)
        self.choose_trainee_comboBox.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.choose_trainee_comboBox.setObjectName("choose_trainee_comboBox")
        self.choose_trainee_label = QtWidgets.QLabel(self.add_training_name)
        self.choose_trainee_label.setGeometry(QtCore.QRect(90, 150, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.choose_trainee_label.setFont(font)
        self.choose_trainee_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.choose_trainee_label.setObjectName("choose_trainee_label")
        self.training_desc_label = QtWidgets.QLabel(self.add_training_name)
        self.training_desc_label.setGeometry(QtCore.QRect(90, 400, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.training_desc_label.setFont(font)
        self.training_desc_label.setStyleSheet("border-bottom: 1px solid white;\n"
"padding-bottom: 10px;")
        self.training_desc_label.setObjectName("training_desc_label")
        self.move_to_add_exercises_button = QtWidgets.QPushButton(self.add_training_name)
        self.move_to_add_exercises_button.setGeometry(QtCore.QRect(640, 550, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.move_to_add_exercises_button.setFont(font)
        self.move_to_add_exercises_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.move_to_add_exercises_button.setObjectName("move_to_add_exercises_button")
        self.start_date_training_dateEdit = QtWidgets.QDateEdit(self.add_training_name)
        self.start_date_training_dateEdit.setGeometry(QtCore.QRect(350, 250, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start_date_training_dateEdit.setFont(font)
        self.start_date_training_dateEdit.setStyleSheet("background: transparent;\n"
"border: none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"padding-left: 10px;\n"
"padding-bottom: 5px;")
        self.start_date_training_dateEdit.setObjectName("start_date_training_dateEdit")
        self.training_desc_lineEdit = QtWidgets.QPlainTextEdit(self.add_training_name)
        self.training_desc_lineEdit.setGeometry(QtCore.QRect(340, 320, 241, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.training_desc_lineEdit.setFont(font)
        self.training_desc_lineEdit.setObjectName("training_desc_lineEdit")
        self.stackedWidget.addWidget(self.add_training_name)
        self.list_of_trainees_page = QtWidgets.QWidget()
        self.list_of_trainees_page.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"color: white;")
        self.list_of_trainees_page.setObjectName("list_of_trainees_page")
        self.list_of_trainees = QtWidgets.QListView(self.list_of_trainees_page)
        self.list_of_trainees.setGeometry(QtCore.QRect(230, 190, 381, 281))
        self.list_of_trainees.setStyleSheet("background-color: rgb(71, 71, 71);\n"
"color: rgb(255, 255, 255);")
        self.list_of_trainees.setObjectName("list_of_trainees")
        self.title_list = QtWidgets.QLabel(self.list_of_trainees_page)
        self.title_list.setGeometry(QtCore.QRect(70, 70, 360, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.title_list.setFont(font)
        self.title_list.setStyleSheet("")
        self.title_list.setObjectName("title_list")
        self.refresh_button = QtWidgets.QPushButton(self.list_of_trainees_page)
        self.refresh_button.setGeometry(QtCore.QRect(560, 140, 51, 41))
        self.refresh_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.refresh_button.setText("")
        self.refresh_button.setObjectName("refresh_button")
        self.add_trainee_list_button = QtWidgets.QPushButton(self.list_of_trainees_page)
        self.add_trainee_list_button.setGeometry(QtCore.QRect(500, 500, 221, 41))
        self.add_trainee_list_button.setStyleSheet("background-color: rgba(30, 29, 29, 130);\n"
"border: 0px;\n"
"border-radius: 10px;")
        self.add_trainee_list_button.setObjectName("add_trainee_list_button")
        self.delete_trainee_button = QtWidgets.QPushButton(self.view_trainee_page)
        self.delete_trainee_button.setObjectName(u"delete_trainee_button")
        self.delete_trainee_button.setGeometry(QtCore.QRect(680, 40, 151, 41))
        self.delete_trainee_button.setStyleSheet(u"background-color: rgba(255, 0, 0, 90);\n"
                                                 "border: 0px;\n"
                                                 "border-radius: 10px;")
        self.stackedWidget.addWidget(self.list_of_trainees_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-1, 0, 1091, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.frame.raise_()
        self.frame_top_menus.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.list_of_trainees_navbutton.setText(_translate("MainWindow", "  Podopieczni"))
        self.add_training_navbutton.setText(_translate("MainWindow", " Treningi"))
        self.generate_report_navbutton.setText(_translate("MainWindow", "   Raport"))
        self.menu_navbutton.setText(_translate("MainWindow", "  Menu"))
        self.instruction_button.setText(_translate("MainWindow", "Zobacz jak\n"
"wykonywać zdjęcia"))
        self.label.setText(_translate("MainWindow", "Witaj,"))
        self.label_5.setText(_translate("MainWindow", "zapoznaj się z dostępnymi opcjami."))
        self.label_6.setText(_translate("MainWindow", "Podopieczni"))
        self.label_9.setText(_translate("MainWindow", "Wyświetl listę lub dodaj nowego\n"
"podopiecznego"))
        self.label_8.setText(_translate("MainWindow", "Trening"))
        self.label_10.setText(_translate("MainWindow", "Dodaj trening i przeglądaj obecne"))
        self.label_11.setText(_translate("MainWindow", "Raport"))
        self.label_12.setText(_translate("MainWindow", "Wygeneruj raport na podstawie zdjęć i zapisz w formacie PDF."))
        self.name_lineEdit.setPlaceholderText(_translate("MainWindow", "Jan"))
        self.name_label.setText(_translate("MainWindow", "Imie"))
        self.surname_label.setText(_translate("MainWindow", "Nazwisko"))
        self.date_of_birth_label.setText(_translate("MainWindow", "Data urodzenia"))
        self.email_label.setText(_translate("MainWindow", "Email"))
        self.add_start_date_training_label.setText(_translate("MainWindow", "Data rozpoczęcia\n"
"treningów"))
        self.phone_label.setText(_translate("MainWindow", "Numer telefonu"))
        self.squat_label.setText(_translate("MainWindow", "Przysiad"))
        self.benchpress_label.setText(_translate("MainWindow", "Wyciskanie leżąc"))
        self.deadlift_label.setText(_translate("MainWindow", "Martwy ciąg"))
        self.add_trainee_title.setText(_translate("MainWindow", "WYPEŁNIJ DANE"))
        self.surname_lineEdit.setPlaceholderText(_translate("MainWindow", "Kowalski"))
        self.email_lineEdit.setPlaceholderText(_translate("MainWindow", "xyz@gmail.com"))
        self.phone_lineEdit.setPlaceholderText(_translate("MainWindow", "887776554"))
        self.PR_title.setText(_translate("MainWindow", "Podaj personalne rekordy"))
        self.benchpress_lineEdit.setPlaceholderText(_translate("MainWindow", "80"))
        self.deadlift_lineEdit.setPlaceholderText(_translate("MainWindow", "120"))
        self.squat_lineEdit.setPlaceholderText(_translate("MainWindow", "100"))
        self.deadlift_kg_label.setText(_translate("MainWindow", "kg"))
        self.benchpress_kg_label.setText(_translate("MainWindow", "kg"))
        self.squat_kg_label.setText(_translate("MainWindow", "kg"))
        self.weight_label.setText(_translate("MainWindow", "Obecna waga"))
        self.weight_lineEdit.setPlaceholderText(_translate("MainWindow", "80"))
        self.squat_kg_label_3.setText(_translate("MainWindow", "kg"))
        self.add_trainee_button.setText(_translate("MainWindow", "+"))
        self.title_generate_report_page.setText(_translate("MainWindow", "GENERUJ RAPORT"))
        self.add_film_button.setText(_translate("MainWindow", "+"))
        self.add_photos_button.setText(_translate("MainWindow", "+"))
        self.report_photo.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "Komentarz"))
        self.prev_photo_button.setText(_translate("MainWindow", "<-"))
        self.next_photo_button.setText(_translate("MainWindow", "->"))
        self.save_report.setText(_translate("MainWindow", "Zapisz raport w PDF"))
        self.title_view_training_page.setText(_translate("MainWindow", "PODGLĄD TRENINGU"))
        self.title_training.setText(_translate("MainWindow", "*****"))
        self.prev_training_button.setText(_translate("MainWindow", "<-"))
        self.next_training_button.setText(_translate("MainWindow", "->"))
        self.email_label_2.setText(_translate("MainWindow", "Email"))
        self.benchpress_label_2.setText(_translate("MainWindow", "Wyciskanie leżąc"))
        self.benchpress_kg_label_2.setText(_translate("MainWindow", "kg"))
        self.date_of_birth_label_2.setText(_translate("MainWindow", "Data urodzenia"))
        self.squat_label_2.setText(_translate("MainWindow", "Przysiad"))
        self.phone_label_2.setText(_translate("MainWindow", "Numer telefonu"))
        self.PR_title_2.setText(_translate("MainWindow", "Podaj personalne rekordy"))
        self.weight_kg_label.setText(_translate("MainWindow", "kg"))
        self.name_surname_dblabel.setText(_translate("MainWindow", "*IMIE I NAZWISKO*"))
        self.weight_label_2.setText(_translate("MainWindow", "Obecna waga"))
        self.squat_kg_label_2.setText(_translate("MainWindow", "kg"))
        self.add_start_date_training_label_2.setText(_translate("MainWindow", "Data rozpoczęcia\n"
"treningów"))
        self.deadlift_label_2.setText(_translate("MainWindow", "Martwy ciąg"))
        self.date_of_birth_label_dblabel.setText(_translate("MainWindow", "*DATA URODZENIA*"))
        self.email_dblabel.setText(_translate("MainWindow", "*EMAIL*"))
        self.phone_dblabel.setText(_translate("MainWindow", "*NUMER*"))
        self.weight_dblabel.setText(_translate("MainWindow", "*WAGA*"))
        self.start_date_training_db_label.setText(_translate("MainWindow", "*DATA*"))
        self.squat_dblabel.setText(_translate("MainWindow", "*przysiad*"))
        self.benchpress_dblabel.setText(_translate("MainWindow", "*wyciskanie*"))
        self.deadlift_dblabel.setText(_translate("MainWindow", "*ciąg*"))
        self.deadlift_kg_label_3.setText(_translate("MainWindow", "kg"))
        self.add_training_trainee_button.setText(_translate("MainWindow", "+ DODAJ TRENING"))
        self.render_film_button.setText(_translate("MainWindow", "Renderuj film"))
        self.render_photos_button.setText(_translate("MainWindow", "Renderuj zdjęcia"))
        self.show_training_trainee_button.setText(_translate("MainWindow", "PODGLĄD TRENINGU"))
        self.title_add_trainig_page.setText(_translate("MainWindow", "WYPEŁNIJ DANE"))
        self.number_of_reps_lineEdit.setPlaceholderText(_translate("MainWindow", "6"))
        self.name_of_exercise_lineEdit.setPlaceholderText(_translate("MainWindow", "Przysiady"))
        self.number_of_sets_label.setText(_translate("MainWindow", "Ilość serii"))
        self.number_of_reps_label.setText(_translate("MainWindow", "Ilość powtórzeń"))
        self.name_of_exercise_label.setText(_translate("MainWindow", "Nazwa ćwiczenia"))
        self.number_of_sets_lineEdit.setPlaceholderText(_translate("MainWindow", "5"))
        self.additional_info_label.setText(_translate("MainWindow", "Dodatkowe informacje"))
        self.add_training_button.setText(_translate("MainWindow", "DODAJ TRENING"))
        self.add_next_excercise_button.setText(_translate("MainWindow", "+ DODAJ KOLEJNE ĆWICZENIE"))
        self.start_date_training_label_2.setText(_translate("MainWindow", "Data rozpoczęcia treningu"))
        self.name_of_training.setText(_translate("MainWindow", "Nazwa treningu"))
        self.name_of_training_lineEdit.setPlaceholderText(_translate("MainWindow", "Trening A"))
        self.add_training_title.setText(_translate("MainWindow", "NAZWIJ TRENING"))
        self.choose_trainee_comboBox.setPlaceholderText(_translate("MainWindow", "Jan Kowalski"))
        self.choose_trainee_label.setText(_translate("MainWindow", "Wybierz podopiecznego"))
        self.training_desc_label.setText(_translate("MainWindow", "Opis treningu"))
        self.move_to_add_exercises_button.setText(_translate("MainWindow", "+"))
        self.title_list.setText(_translate("MainWindow", "LISTA PODOPIECZNYCH"))
        self.add_trainee_list_button.setText(_translate("MainWindow", "+ DODAJ PODOPIECZNEGO"))
        self.delete_trainee_button.setText(_translate("MainWindow", u"Usu\u0144 podopiecznego"))
        self.label_2.setText(_translate("MainWindow", "trainerAdvisor."))
